### ISSUE TITLE
``pip search`` results in internal server error

### ISSUE THREAD

**Issue by nisavid** [benliles/djangopypi#13]
pip supports specifying a custom cheeseshop when performing a search.  this takes the form `pip search --index {cheeseshop} {query}`.  however, when i try to use this, my chishop instance responds with an internal server error:

```
$ pip search --index http://localhost:8333/pypi foo
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/search.py", line 33, in run
    pypi_hits = self.search(query, index_url)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/search.py", line 44, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1575, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1312, in single_request
    response.msg,
ProtocolError: <ProtocolError for localhost:8333/pypi: 500 INTERNAL SERVER ERROR>

Storing complete log in /home/ivan/.pip/pip.log
```

meanwhile, chishop outputs a line like this:
`[05/Aug/2011 18:25:17] "POST /pypi HTTP/1.1" 500 75674`

that's with a chishop instance running on localhost, invoked as `bin/django runserver -v 2 8333`.  i have customized a few, but not many, of the chishop settings.  if you'd like, i can provide a complete minimal working example.

**Comment by tomwys** [comment]
I have checked in my configuration and error not occurred. Can you give us trackback from server? You can install sentry to get it (http://readthedocs.org/docs/sentry/en/latest/index.html).

**Comment by benliles** [comment]
Your index location needs to have a trailing slash. Currently, search is not supported over the XML-RPC interface anyway, so you'll get a 405 error instead of 500.
