### ISSUE TITLE
OSX El Capitan Issue

### ISSUE THREAD

**Issue by johnphillips1992** [benliles/djangopypi#56]
When I do a "setup.py sdist bdist_egg upload" after upgrading to El Capitan the Post Data has 

u':action': [u'\r\nfile_upload\r']

Which fails when you do a string compare for the 'file_upload' command

**Comment by johnphillips1992** [comment]
2015-10-16 15:45:26,734 ERROR   djangopypi.views.distutils: Failure when storing upload
Traceback (most recent call last):
  File "/var/www/pypi_arch/eggs/djangopypi-0.4.5-py2.7.egg/djangopypi/views/distutils.py", line 103, in register_or_upload
    md5_digest=md5_digest)
  File "/var/www/pypi_arch/eggs/Django-1.3.7-py2.7.egg/django/db/models/manager.py", line 138, in create
    return self.get_query_set().create(*_kwargs)
  File "/var/www/pypi_arch/eggs/Django-1.3.7-py2.7.egg/django/db/models/query.py", line 360, in create
    obj.save(force_insert=True, using=self.db)
  File "/var/www/pypi_arch/eggs/Django-1.3.7-py2.7.egg/django/db/models/base.py", line 460, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/var/www/pypi_arch/eggs/Django-1.3.7-py2.7.egg/django/db/models/base.py", line 553, in save_base
    result = manager._insert(values, return_id=update_pk, using=using)
  File "/var/www/pypi_arch/eggs/Django-1.3.7-py2.7.egg/django/db/models/manager.py", line 195, in _insert
    return insert_query(self.model, values, *_kwargs)
  File "/var/www/pypi_arch/eggs/Django-1.3.7-py2.7.egg/django/db/models/query.py", line 1436, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/var/www/pypi_arch/eggs/Django-1.3.7-py2.7.egg/django/db/models/sql/compiler.py", line 791, in execute_sql
    cursor = super(SQLInsertCompiler, self).execute_sql(None)
  File "/var/www/pypi_arch/eggs/Django-1.3.7-py2.7.egg/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/pypi_arch/eggs/Django-1.3.7-py2.7.egg/django/db/backends/postgresql_psycopg2/base.py", line 44, in execute
    return self.cursor.execute(query, args)
DatabaseError: value too long for type character varying(32)

**Comment by johnphillips1992** [comment]
Getting that error now...
